#!/usr/bin/env python3
import argparse
import os
import sys
import pandas as pd
from vancouver_bike_theft.utils import decompose_filepath


def normalize(input, std_data):
    tr_df = pd.read_csv(std_data)

    tr_df.drop(
        columns=["id", "left", "top", "right", "bottom", "NUM_Thefts"], inplace=True
    )

    minimums = {col: tr_df[col].min() for col in tr_df.columns}
    maximums = {col: tr_df[col].max() for col in tr_df.columns}

    df = pd.read_csv(input)

    for col in df.columns:
        if col in ["id", "left", "top", "right", "bottom", "NUM_Thefts"]:
            continue
        df[col] = (df[col] - minimums[col]) / (maximums[col] - minimums[col])

    return df


def main(args):
    if os.path.isfile(args.input) == False or os.path.isfile(args.std_data) == False:
        print("File(s) not existing", file=sys.stderr)
        sys.exit(1)

    dir_path, filename, _ = decompose_filepath(args.input)

    df = normalize(args.input, args.std_data)

    out = f"{dir_path}/{filename}_norm.csv"

    df.to_csv(out, index=False)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--input", type=str, help="Path of dataset to be normalized")
    parser.add_argument(
        "--std-data", type=str, help="Dataset that provides normalization standard"
    )

    args = parser.parse_args()
    main(args)
